// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type FollowUser struct {
	ID          interface{}
	CreatedAt   time.Time
	AccountName string
	Hashtag     string
	Puuid       string
	Region      string
}

type GuildCount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int64
}

type UsersCount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int64
}
