// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Guildcount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int32
}

type Userscount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int32
}
