// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type FollowUser struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	AccountName string
	Hashtag     string
	Puuid       string
	Region      string
}

type Guildcount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int32
}

type Userscount struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Count     int32
}
